spring.ai.openai.api-key=${OPENAI_API_KEY:YOUR_OPENAI_API_KEY}
spring.datasource.url=jdbc:mysql://localhost:3306/call_analyzer
spring.datasource.username=root
spring.datasource.password=MYSQL.root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect